name: 'Publish Alpha Version'

on:
  push:
    branches:
      - pnpm
    paths-ignore:
      - '**/package.json'

jobs:
  publish:
    name: 🚀 Publishing to NPM
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [core, react, solid, svelte]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Set variables
        run: |
          echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(npm view ./packages/${{ matrix.package }} version)" >> $GITHUB_ENV

      - name: Build packages
        run: |
          pnpm
          pnpm build

      - name: Publish packages
        run: |
          pnpm --filter=@qr-x/${{ matrix.package }} exec pnpm version ${{ env.VERSION }}-alpha.${{ env.COMMIT_ID }} --no-git-tag-version
          pnpm --filter=@qr-x/${{ matrix.package }} publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
