name: 'Publish Alpha Version'

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**/package.json'
      - '.yarn/versions/**'

jobs:
  publish:
    name: 🚀 Publishing to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Set vars
        run: |
          echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build & Publish
        run: |
          yarn
          yarn build
          yarn workspaces foreach --since --include @qr-x/\* run echo "VERSION=$(npm view ./ version)" >> $GITHUB_ENV && version ${{ env.VERSION }}-alpha.78051f4
          yarn workspaces foreach --since --include @qr-x/\* npm publish --tag alpha --access public --force
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
